kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3-openjdk-17
    commands:
      - mvn -B -DskipTests clean install
      - mvn test -B
    volumes:
      - name: m2
        path: /root/.m2

  - name: archive-artifacts
    image: alpine:latest
    commands:
      - mkdir -p /builds/Tihwin
      - cp target/Tihwin-*[0-9].jar /builds/Tihwin/
      - cp target/Tihwin-*[0-9].exe /builds/Tihwin/
    volumes:
      - name: builds
        path: /builds

  - name: make-win-installer
    image: wheatstalk/makensis:3
    commands:
      - cp target/Tihwin-*.exe NSIS/Tihwin.exe
      - NSIS/update_version.sh
      - cd NSIS
      - makensis -V4 ./installer.nsi
      - cp Installer-*.exe /builds/Tihwin/
    volumes:
      - name: builds
        path: /builds
      - name: jdk
        path: /drone/src/NSIS/jdk

volumes:
  - name: m2
    host:
      path: /home/docker/drone/files/m2
  - name: builds
    host:
      path: /home/www/builds
  - name: jdk
    host:
      path: /home/docker/drone/files/assembly/openjdk-19.0.2