steps:
  - name: build
    when:
      event: [ tag, push ]
    image: maven:3-openjdk-17
    commands:
      - mvn -B -DskipTests clean install
      - mvn test -B
    volumes:
      - /home/docker/woodpecker/files/m2:/root/.m2
  - name: archive-artifacts
    image: alpine:latest
    commands:
      - mkdir -p /builds/Tihwin
      - cp target/Tihwin-*[0-9].jar /builds/Tihwin/
      - cp target/Tihwin-*[0-9].exe /builds/Tihwin/
    volumes:
      - /home/www/builds:/builds
  - name: make-win-installer
    when:
      event: [ tag, push ]
    image: wheatstalk/makensis:3
    commands:
      - cp target/Tihwin-*.exe NSIS/Tihwin.exe
      - NSIS/update_version.sh
      - cd NSIS
      - makensis -V4 ./installer.nsi
      - cp Installer-*.exe /builds/Tihwin/
    volumes:
      - /home/www/builds:/builds
      - /home/docker/woodpecker/files/assembly/openjdk-19.0.2:/assembly/jdk